/*
 * Copyright 2022 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.reply.ui.theme

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

//val Purple80 = Color(0xFFD0BCFF)
//val PurpleGrey80 = Color(0xFFCCC2DC)
//val Pink80 = Color(0xFFEFB8C8)
//
//val Purple40 = Color(0xFF6650a4)
//val PurpleGrey40 = Color(0xFF625b71)
//val Pink40 = Color(0xFF7D5260)

val primaryLight = Color(0xFF006E17)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9CFF93)
val onPrimaryContainerLight = Color(0xFF0F791E)
val secondaryLight = Color(0xFF43673F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC4EEBA)
val onSecondaryContainerLight = Color(0xFF496D44)
val tertiaryLight = Color(0xFF006A60)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF6CFFEB)
val onTertiaryContainerLight = Color(0xFF00756A)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF6FBEF)
val onBackgroundLight = Color(0xFF171D16)
val surfaceLight = Color(0xFFF6FBEF)
val onSurfaceLight = Color(0xFF171D16)
val surfaceVariantLight = Color(0xFFDBE6D4)
val onSurfaceVariantLight = Color(0xFF3F4A3C)
val outlineLight = Color(0xFF6F7A6B)
val outlineVariantLight = Color(0xFFBFCAB8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322A)
val inverseOnSurfaceLight = Color(0xFFEDF3E7)
val inversePrimaryLight = Color(0xFF7BDC75)
val surfaceDimLight = Color(0xFFD6DCD0)
val surfaceBrightLight = Color(0xFFF6FBEF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F5E9)
val surfaceContainerLight = Color(0xFFEAF0E4)
val surfaceContainerHighLight = Color(0xFFE4EADE)
val surfaceContainerHighestLight = Color(0xFFDFE4D8)

val primaryLightMediumContrast = Color(0xFF004009)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF197E23)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF1B3D1A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF52764C)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF003E37)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF007B6F)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF6FBEF)
val onBackgroundLightMediumContrast = Color(0xFF171D16)
val surfaceLightMediumContrast = Color(0xFFF6FBEF)
val onSurfaceLightMediumContrast = Color(0xFF0D130C)
val surfaceVariantLightMediumContrast = Color(0xFFDBE6D4)
val onSurfaceVariantLightMediumContrast = Color(0xFF2F392C)
val outlineLightMediumContrast = Color(0xFF4B5547)
val outlineVariantLightMediumContrast = Color(0xFF657061)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2C322A)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEDF3E7)
val inversePrimaryLightMediumContrast = Color(0xFF7BDC75)
val surfaceDimLightMediumContrast = Color(0xFFC3C8BD)
val surfaceBrightLightMediumContrast = Color(0xFFF6FBEF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF0F5E9)
val surfaceContainerLightMediumContrast = Color(0xFFE4EADE)
val surfaceContainerHighLightMediumContrast = Color(0xFFD9DFD3)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCED3C8)

val primaryLightHighContrast = Color(0xFF003506)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF005610)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF113310)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF2E512B)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF00332D)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF00534A)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF6FBEF)
val onBackgroundLightHighContrast = Color(0xFF171D16)
val surfaceLightHighContrast = Color(0xFFF6FBEF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDBE6D4)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF252F23)
val outlineVariantLightHighContrast = Color(0xFF424C3E)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2C322A)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF7BDC75)
val surfaceDimLightHighContrast = Color(0xFFB5BBAF)
val surfaceBrightLightHighContrast = Color(0xFFF6FBEF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEDF3E7)
val surfaceContainerLightHighContrast = Color(0xFFDFE4D8)
val surfaceContainerHighLightHighContrast = Color(0xFFD0D6CB)
val surfaceContainerHighestLightHighContrast = Color(0xFFC3C8BD)

val primaryDark = Color(0xFFFFFFFF)
val onPrimaryDark = Color(0xFF003907)
val primaryContainerDark = Color(0xFF96F98E)
val onPrimaryContainerDark = Color(0xFF07751B)
val secondaryDark = Color(0xFFA9D1A0)
val onSecondaryDark = Color(0xFF153714)
val secondaryContainerDark = Color(0xFF2C4F29)
val onSecondaryContainerDark = Color(0xFF98C090)
val tertiaryDark = Color(0xFFFFFFFF)
val onTertiaryDark = Color(0xFF003731)
val tertiaryContainerDark = Color(0xFF65F9E5)
val onTertiaryContainerDark = Color(0xFF007166)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F150E)
val onBackgroundDark = Color(0xFFDFE4D8)
val surfaceDark = Color(0xFF0F150E)
val onSurfaceDark = Color(0xFFDFE4D8)
val surfaceVariantDark = Color(0xFF3F4A3C)
val onSurfaceVariantDark = Color(0xFFBFCAB8)
val outlineDark = Color(0xFF899484)
val outlineVariantDark = Color(0xFF3F4A3C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDFE4D8)
val inverseOnSurfaceDark = Color(0xFF2C322A)
val inversePrimaryDark = Color(0xFF006E17)
val surfaceDimDark = Color(0xFF0F150E)
val surfaceBrightDark = Color(0xFF353B33)
val surfaceContainerLowestDark = Color(0xFF0A1009)
val surfaceContainerLowDark = Color(0xFF171D16)
val surfaceContainerDark = Color(0xFF1B211A)
val surfaceContainerHighDark = Color(0xFF262C24)
val surfaceContainerHighestDark = Color(0xFF31362E)

val primaryDarkMediumContrast = Color(0xFFFFFFFF)
val onPrimaryDarkMediumContrast = Color(0xFF003907)
val primaryContainerDarkMediumContrast = Color(0xFF96F98E)
val onPrimaryContainerDarkMediumContrast = Color(0xFF00540F)
val secondaryDarkMediumContrast = Color(0xFFBEE7B5)
val onSecondaryDarkMediumContrast = Color(0xFF092C0A)
val secondaryContainerDarkMediumContrast = Color(0xFF749A6D)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFFFFF)
val onTertiaryDarkMediumContrast = Color(0xFF003731)
val tertiaryContainerDarkMediumContrast = Color(0xFF65F9E5)
val onTertiaryContainerDarkMediumContrast = Color(0xFF005249)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F150E)
val onBackgroundDarkMediumContrast = Color(0xFFDFE4D8)
val surfaceDarkMediumContrast = Color(0xFF0F150E)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3F4A3C)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD4E0CE)
val outlineDarkMediumContrast = Color(0xFFAAB5A4)
val outlineVariantDarkMediumContrast = Color(0xFF889483)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDFE4D8)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF262C24)
val inversePrimaryDarkMediumContrast = Color(0xFF00540F)
val surfaceDimDarkMediumContrast = Color(0xFF0F150E)
val surfaceBrightDarkMediumContrast = Color(0xFF40463E)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF040904)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191F18)
val surfaceContainerDarkMediumContrast = Color(0xFF242922)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2E342C)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF393F37)

val primaryDarkHighContrast = Color(0xFFFFFFFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF96F98E)
val onPrimaryContainerDarkHighContrast = Color(0xFF003206)
val secondaryDarkHighContrast = Color(0xFFD1FBC7)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFA5CD9C)
val onSecondaryContainerDarkHighContrast = Color(0xFF000F01)
val tertiaryDarkHighContrast = Color(0xFFFFFFFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF65F9E5)
val onTertiaryContainerDarkHighContrast = Color(0xFF00302B)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0F150E)
val onBackgroundDarkHighContrast = Color(0xFFDFE4D8)
val surfaceDarkHighContrast = Color(0xFF0F150E)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3F4A3C)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE8F4E1)
val outlineVariantDarkHighContrast = Color(0xFFBBC6B4)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDFE4D8)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF00540F)
val surfaceDimDarkHighContrast = Color(0xFF0F150E)
val surfaceBrightDarkHighContrast = Color(0xFF4C5249)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1B211A)
val surfaceContainerDarkHighContrast = Color(0xFF2C322A)
val surfaceContainerHighDarkHighContrast = Color(0xFF373D35)
val surfaceContainerHighestDarkHighContrast = Color(0xFF434840)